### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by Pabloutndev** [pdepjm/2024-tp0-presentacion-EzequielSecchi#1]
Felicitaciones por el curso de reparacion de pc y muy copado la idea de desarrollar un videojuego!, si te interesa también la programación de C en videojuegos, hay una libreria interesante llamada opengl, pero godot o unity son mas completos para desarrollo.

Sugerencia, colocar algun gusto musical que tengas o alguna banda que hayas escuchado hace poco.

**Comment by EzequielSecchi** [comment]
me copa la idea ¡muchas gracias! y tendré en cuenta en echarle un vistazo a esa librería
